services:
  app:
    build: .
    expose:
      - "8080"
    volumes:
      - ./tasks.db:/app/tasks.db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
